//! `update_spec.toml` からプロジェクト側の Rust 定数を生成する build 補助ライブラリ。
//!
//! プロジェクトの `build.rs` から `generate()` を呼ぶ。ホストツール
//! (`tang-primer-25k-sd-updater-tools`) は `load()` で同じ仕様を読み、package / factory image を生成する。
//! パース・検証のロジックはこの crate が唯一の実装であり、他言語実装との同期は不要。

use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

/// `update_spec.toml` の内容 (ホスト側、`String` 所有)。
///
/// firmware 側の生成定数 [`tang_primer_25k_sd_updater::UpdateSpec`] とは別物。こちらは
/// `tang-primer-25k-sd-updater-tools` がファイルから直接読み込むために使う。
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Spec {
    pub file_name: String,
    pub magic: [u8; 8],
    pub header_size: usize,
    pub format_version: u32,
    pub target_hw_id: u32,
    pub target_fpga_id: u32,
    pub flash_layout_id: u32,
    pub flash_size_bytes: u32,
    pub updater_base: u32,
    pub updater_size: u32,
    pub app_base: u32,
    pub app_size: u32,
    pub metadata_base: u32,
    pub metadata_size: u32,
    pub golden_updater_base_candidate: u32,
    pub golden_updater_size_candidate: u32,
}

/// `update_spec.toml` の生の構造。TOML の型検証 (u32 等) は serde が行う。
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawSpec {
    /// SD から読む固定ファイル名 (FAT32 8.3: 8 文字以内 + 拡張子 3 文字以内)。
    file_name: String,
    /// header 先頭 8 byte の 16 進数 (16 文字)。
    magic_hex: String,
    header_size: u32,
    format_version: u32,
    target_hw_id: u32,
    target_fpga_id: u32,
    flash: RawFlash,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawFlash {
    flash_size_bytes: u32,
    updater_base: u32,
    updater_size: u32,
    app_base: u32,
    app_size: u32,
    metadata_base: u32,
    metadata_size: u32,
    golden_updater_base_candidate: u32,
    golden_updater_size_candidate: u32,
    layout_id: u32,
}

/// `update_spec.toml` の内容文字列を検証して [`Spec`] を返す。`path` はエラーメッセージ用。
pub fn parse(spec: &str, path: &str) -> Result<Spec, String> {
    let raw: RawSpec = toml::from_str(spec).map_err(|error| format!("{path}: {error}"))?;

    let magic = parse_magic(&raw.magic_hex).map_err(|error| format!("{path}: {error}"))?;
    if !raw
        .file_name
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || byte == b'.')
    {
        return Err(format!("{path}: invalid file_name \"{}\"", raw.file_name));
    }

    Ok(Spec {
        file_name: raw.file_name,
        magic,
        header_size: raw.header_size as usize,
        format_version: raw.format_version,
        target_hw_id: raw.target_hw_id,
        target_fpga_id: raw.target_fpga_id,
        flash_layout_id: raw.flash.layout_id,
        flash_size_bytes: raw.flash.flash_size_bytes,
        updater_base: raw.flash.updater_base,
        updater_size: raw.flash.updater_size,
        app_base: raw.flash.app_base,
        app_size: raw.flash.app_size,
        metadata_base: raw.flash.metadata_base,
        metadata_size: raw.flash.metadata_size,
        golden_updater_base_candidate: raw.flash.golden_updater_base_candidate,
        golden_updater_size_candidate: raw.flash.golden_updater_size_candidate,
    })
}

/// `update_spec.toml` を読み、検証して [`Spec`] を返す。
pub fn load(spec_path: &str) -> Result<Spec, String> {
    let spec = fs::read_to_string(spec_path)
        .map_err(|error| format!("{spec_path}: failed to read: {error}"))?;
    parse(&spec, spec_path)
}

/// `update_spec.toml` を読み、`$OUT_DIR/update_spec.rs` に `SPEC` 定数を生成する。
///
/// 生成コードは `tang_primer_25k_sd_updater::UpdateSpec` を参照するため、依存 crate の名前は
/// `tang_primer_25k_sd_updater` にする必要がある。`cargo:rerun-if-changed=update_spec.toml` の emit は
/// build-dependency の stdout が転送されないため、呼び出し側の build.rs で行うこと。
pub fn generate(spec_path: &str) -> Result<(), String> {
    let spec = load(spec_path)?;
    let generated = generate_rust(&spec)?;

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").ok_or("OUT_DIR is not set")?);
    fs::write(out_dir.join("update_spec.rs"), generated)
        .map_err(|error| format!("failed to write generated spec: {error}"))?;
    Ok(())
}

fn parse_magic(hex: &str) -> Result<[u8; 8], String> {
    if hex.len() != 16 {
        return Err(format!(
            "magic_hex must be 16 hex chars (8 bytes), got \"{hex}\""
        ));
    }

    let mut bytes = [0; 8];
    for (index, byte) in bytes.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&hex[index * 2..index * 2 + 2], 16)
            .map_err(|_| format!("magic_hex contains non-hex chars: \"{hex}\""))?;
    }
    Ok(bytes)
}

fn generate_rust(spec: &Spec) -> Result<String, String> {
    let magic = spec
        .magic
        .iter()
        .map(u8::to_string)
        .collect::<Vec<_>>()
        .join(", ");

    Ok(format!(
        "\
// This file is generated by tang-primer-25k-sd-updater-build from update_spec.toml. Do not edit.
// The generated code refers to tang_primer_25k_sd_updater::UpdateSpec, so the dependency
// crate must be named tang_primer_25k_sd_updater.
pub const SPEC: tang_primer_25k_sd_updater::UpdateSpec = tang_primer_25k_sd_updater::UpdateSpec {{
    file_name: \"{file_name}\",
    magic: [{magic}],
    header_size: {header_size},
    format_version: {format_version},
    target_hw_id: {target_hw_id},
    target_fpga_id: {target_fpga_id},
    flash_layout_id: {layout_id},
    flash_size_bytes: {flash_size_bytes},
    updater_base: {updater_base},
    updater_size: {updater_size},
    app_base: {app_base},
    app_size: {app_size},
    metadata_base: {metadata_base},
    metadata_size: {metadata_size},
    golden_updater_base_candidate: {golden_updater_base_candidate},
    golden_updater_size_candidate: {golden_updater_size_candidate},
}};
",
        file_name = spec.file_name,
        header_size = spec.header_size,
        format_version = spec.format_version,
        target_hw_id = spec.target_hw_id,
        target_fpga_id = spec.target_fpga_id,
        flash_size_bytes = spec.flash_size_bytes,
        updater_base = spec.updater_base,
        updater_size = spec.updater_size,
        app_base = spec.app_base,
        app_size = spec.app_size,
        metadata_base = spec.metadata_base,
        metadata_size = spec.metadata_size,
        golden_updater_base_candidate = spec.golden_updater_base_candidate,
        golden_updater_size_candidate = spec.golden_updater_size_candidate,
        layout_id = spec.flash_layout_id,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_TOML: &str = "\
# sample spec
file_name = \"TANG25K.UPD\"
magic_hex = \"54414e4732354b00\"
header_size = 0x58
format_version = 1
target_hw_id = 0x5432354b
target_fpga_id = 0x47573541

[flash]
flash_size_bytes = 0x800000
updater_base = 0x000000
updater_size = 0x100000
app_base = 0x100000
app_size = 0x100000
metadata_base = 0x200000
metadata_size = 0x010000
golden_updater_base_candidate = 0x700000
golden_updater_size_candidate = 0x100000
layout_id = 0x4c415931
";

    #[test]
    fn parses_valid_spec() {
        let spec = parse(SAMPLE_TOML, "update_spec.toml").unwrap();
        assert_eq!(spec.file_name, "TANG25K.UPD");
        assert_eq!(spec.app_base, 0x100000);
        assert_eq!(spec.header_size, 0x58);
        assert_eq!(spec.magic, [0x54, 0x41, 0x4E, 0x47, 0x32, 0x35, 0x4B, 0x00]);
    }

    #[test]
    fn rejects_missing_key() {
        let spec = SAMPLE_TOML.replace("layout_id = 0x4c415931\n", "");
        assert!(parse(&spec, "update_spec.toml").is_err());
    }

    #[test]
    fn rejects_unknown_key() {
        let spec = format!("{SAMPLE_TOML}extra_key = 1\n");
        assert!(parse(&spec, "update_spec.toml").is_err());
    }

    #[test]
    fn rejects_non_u32_value() {
        let spec = SAMPLE_TOML.replace("header_size = 0x58", "header_size = -1");
        assert!(parse(&spec, "update_spec.toml").is_err());
    }

    #[test]
    fn rejects_invalid_file_name() {
        let spec = SAMPLE_TOML.replace("file_name = \"TANG25K.UPD\"", "file_name = \"../x\"");
        assert!(parse(&spec, "update_spec.toml").is_err());
    }

    #[test]
    fn rejects_bad_magic_length() {
        let spec = SAMPLE_TOML.replace("magic_hex = \"54414e4732354b00\"", "magic_hex = \"ff\"");
        assert!(parse(&spec, "update_spec.toml").is_err());
    }

    #[test]
    fn rejects_non_hex_magic() {
        let spec = SAMPLE_TOML.replace(
            "magic_hex = \"54414e4732354b00\"",
            "magic_hex = \"zzzzzzzzzzzzzzzz\"",
        );
        assert!(parse(&spec, "update_spec.toml").is_err());
    }

    #[test]
    fn generates_const_with_crate_reference() {
        let spec = parse(SAMPLE_TOML, "update_spec.toml").unwrap();
        let generated = generate_rust(&spec).unwrap();
        assert!(generated.contains("pub const SPEC: tang_primer_25k_sd_updater::UpdateSpec"));
        assert!(generated.contains("file_name: \"TANG25K.UPD\""));
    }
}
